#!/usr/bin/env Rscript
#' GetDataAsset
#'
#' Downloads, unzips, and loads the data asset stored at the following Dropbox link:
#' https://www.dropbox.com/s/5mzc60tbh09ew49/lalonde%20nsw.csv.zip?dl=0
#'
#' @usage
#'
#' GetDataAsset()
#'
#' @param url character string with the URL housing the data object.
#'
#' @param target_extension (default = `".csv"`) character string describing
#' the target extension of the file in the downloaded .zip folder.
#'
#' @return `z` The downloaded data object from the URL.
#' @export
#'
#' @details `GetDataAsset` downloads the zipped `.csv` file and loads it into memory based on the input URL.
#'
#'
#' @export
#'
#' @md
